#!/bin/bash

set -eu
trap exit INT TERM

TARGET_PACKAGE=""

while [ $# -gt 0 ] ; do
key="$1"

case $key in

  --pkg)
    TARGET_PACKAGE="$2"
    shift
    shift
  ;;

  *)
    shift
  ;;

esac
done

if [ ! "${TARGET_PACKAGE}" ] ; then
  (>&2 echo "[error] target package not provided")
  exit 1
fi

cd /go/src/github.com/jancajthaml-openbank/${TARGET_PACKAGE}

if [ -d vendor ] ; then
  rm -rf vendor
fi

if [ -f go.sum ] ; then
  rm -f go.sum
fi

GO111MODULE=on \
  go mod verify

GO111MODULE=on \
  go mod tidy

GO111MODULE=on \
  go mod vendor
