#!/bin/bash

set -eu
trap exit INT TERM

################################################################################

TARGET_PACKAGE=""
while [ $# -gt 0 ] ; do
key="$1"
case $key in
  --pkg)  TARGET_PACKAGE="$2";  shift; shift; ;;
  *)                            shift;        ;;
esac
done

################################################################################

if [ -z "${TARGET_PACKAGE}" ] ; then
  (>&2 echo "[error] target package not provided")
  exit 1
fi

################################################################################

lifecycle::go::sync() {
  local dir="$1"
  if [ -z ${dir} -o ! -d ${dir} ] ; then
    return
  fi

  if [ -d ${dir}/vendor ] ; then
    rm -rf ${dir}/vendor
  fi

  if [ -f ${dir}/go.sum ] ; then
    rm -f ${dir}/go.sum
  fi

  cd ${dir} && GO111MODULE=on go mod verify
  cd ${dir} && GO111MODULE=on go mod tidy
  cd ${dir} && GO111MODULE=on go mod vendor
}

################################################################################

lifecycle::go::sync \
  ${GOPATH}/src/github.com/jancajthaml-openbank/${TARGET_PACKAGE}
