#!/bin/bash

set -e
trap exit INT TERM

TARGET_PACKAGE=""
OUTPUT=""

while [ $# -gt 0 ] ; do
key="$1"

case $key in

  --pkg)
    TARGET_PACKAGE="$2"
    shift
    shift
  ;;

  --output)
    OUTPUT="$2"
    shift
    shift
  ;;

  *)
    shift
  ;;

esac
done

if [ -z "${TARGET_PACKAGE}" ] ; then
  (>&2 echo "[error] target package not provided")
  exit 1
fi

if [ -z "${OUTPUT}" ] ; then
  (>&2 echo "[error] output not provided")
  exit 1
fi

coverage_out=$(tempfile)
test_out=$(tempfile)

mkdir -p ${OUTPUT} ${OUTPUT}/unit-tests-${TARGET_PACKAGE}
cd ${GOPATH}/src/github.com/jancajthaml-openbank/${TARGET_PACKAGE}

# run unit tests and collect coverage

2>&1 GOMAXPROCS=1 \
  grc go test \
  -v ./... \
  -coverprofile=${coverage_out} \
  -coverpkg=./... \
  -timeout=20s | tee ${test_out}

# remove anscii colors from file
sed -i 's/\x1b\[[0-9;]*m//g' ${test_out}

go2xunit \
  -fail \
  -input ${test_out} \
  -output ${OUTPUT}/unit-tests-${TARGET_PACKAGE}/results.xml

go tool cover \
  --html=${coverage_out} \
  -o ${OUTPUT}/unit-tests-${TARGET_PACKAGE}/coverage.html

# run only benchmarks

GOMAXPROCS=1 \
  grc go test \
  -v ./... \
  -run=^$ \
  -bench=. \
  -benchmem \
  -timeout=1m
