version: '2.1'

# ---------------------------------------------------------------------------- #

services:

  # -------------------------------------------------------------------------- #

  go:
    image: jancajthaml/go
    volumes:
      - .:/project
      - ./services/ledger-unit:/go/src/github.com/jancajthaml-openbank/ledger-unit
      - ./services/ledger-rest:/go/src/github.com/jancajthaml-openbank/ledger-rest
    working_dir: /project
    environment:
      - GOOS
      - GOARCH
      - GOPATH=/go
      - COMPOSE_PROJECT_NAME
    entrypoint: ["go"]
    tty: true

  # -------------------------------------------------------------------------- #

  sync:
    extends: go
    entrypoint: ["/project/dev/lifecycle/sync"]

  # -------------------------------------------------------------------------- #

  update:
    extends: go
    entrypoint: ["/project/dev/lifecycle/update"]

  # -------------------------------------------------------------------------- #

  lint:
    extends: go
    entrypoint: ["/project/dev/lifecycle/lint"]

  # -------------------------------------------------------------------------- #

  sec:
    extends: go
    entrypoint: ["/project/dev/lifecycle/sec"]

  # -------------------------------------------------------------------------- #

  package:
    extends: go
    entrypoint: ["/project/dev/lifecycle/package"]

  # -------------------------------------------------------------------------- #

  release:
    extends: go
    entrypoint: ["/project/dev/lifecycle/release"]

  # -------------------------------------------------------------------------- #

  debian:
    extends: go
    entrypoint: ["/project/dev/lifecycle/debian"]

  # -------------------------------------------------------------------------- #

  test:
    extends: go
    entrypoint: ["/project/dev/lifecycle/test"]

  # -------------------------------------------------------------------------- #

  bbtest:
    image: jancajthaml/bbtest:amd64
    environment:
      IMAGE_VERSION: ${VERSION:-latest}-${META:-master}
      UNIT_VERSION: ${VERSION:-latest}
      UNIT_ARCH: amd64
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /var/lib/docker/containers:/var/lib/docker/containers:rw
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./bbtest:/opt/app
      - ./reports:/tmp/reports
    working_dir: /opt/app

# ---------------------------------------------------------------------------- #
