version: '3.7'

# ---------------------------------------------------------------------------- #

services:

  # -------------------------------------------------------------------------- #

  go: &go
    image: jancajthaml/go
    tty: true
    volumes:
      - .:/project
      - ./services/ledger-unit:/go/src/github.com/jancajthaml-openbank/ledger-unit
      - ./services/ledger-rest:/go/src/github.com/jancajthaml-openbank/ledger-rest
    working_dir: /project
    environment:
      - GOOS
      - GOARCH
      - GOPATH=/go
      - COMPOSE_PROJECT_NAME

  # -------------------------------------------------------------------------- #

  debian: &debian
    image: jancajthaml/debian-packager
    tty: true
    volumes:
      - .:/project
    working_dir: /project

  # -------------------------------------------------------------------------- #

  sync:
    <<: *go
    entrypoint:
      - /project/dev/lifecycle/sync

  # -------------------------------------------------------------------------- #

  update:
    <<: *go
    entrypoint:
      - /project/dev/lifecycle/update

  # -------------------------------------------------------------------------- #

  lint:
    <<: *go
    entrypoint:
      - /project/dev/lifecycle/lint

  # -------------------------------------------------------------------------- #

  sec:
    <<: *go
    entrypoint:
      - /project/dev/lifecycle/sec

  # -------------------------------------------------------------------------- #

  package:
    <<: *go
    entrypoint:
      - /project/dev/lifecycle/package

  # -------------------------------------------------------------------------- #

  release:
    <<: *debian
    entrypoint:
      - /project/dev/lifecycle/release

  # -------------------------------------------------------------------------- #

  debian-package:
    <<: *debian
    entrypoint:
      - /project/dev/lifecycle/debian

  # -------------------------------------------------------------------------- #

  test:
    <<: *go
    entrypoint:
      - /project/dev/lifecycle/test

  # -------------------------------------------------------------------------- #

  bbtest:
    image: jancajthaml/bbtest:amd64
    environment:
      IMAGE_VERSION: ${IMAGE_VERSION:-}
      UNIT_VERSION: ${UNIT_VERSION:-}
      UNIT_ARCH: amd64
      CI: ${CI:-false}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /var/lib/docker/containers:/var/lib/docker/containers:rw
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - .:/opt/app
    working_dir: /opt/app

# ---------------------------------------------------------------------------- #
