#!/bin/sh

set -e

delete() {
  if [ -f "${1}" ] ; then
    rm "${1}"
  fi
}

delete_service_files() {
  delete /etc/systemd/ledger.service.wants/ledger-rest.service
  delete /lib/systemd/system/ledger-rest.service

  delete /etc/systemd/ledger.service.wants/ledger-unit@.service
  delete /lib/systemd/system/ledger-unit@.service

  delete /etc/systemd/ledger.service.wants/ledger.path
  delete /lib/systemd/system/ledger.path

  delete /etc/systemd/multi-user.target.wants/ledger.service
  delete /lib/systemd/system/ledger.service
}

delete_displace_files() {
  delete /etc/init/ledger.conf
}

case "$1" in

  purge)
    delete_service_files
    delete_displace_files
    (systemctl daemon-reload >/dev/null 2>&1 || :)
    (systemctl reset-failed >/dev/null 2>&1 || :)
  ;;

  remove)
    (systemctl -a -t service --no-legend  | awk '$1 ~ /ledger/ { print $1 }' | xargs -I {} systemctl stop {} 2> /dev/null || :)
    delete_displace_files
    (systemctl daemon-reload >/dev/null 2>&1 || :)
  ;;

  upgrade|deconfigure)
    (systemctl stop ledger >/dev/null 2>&1 || :)
  ;;

  remove|failed-upgrade|abort-install|abort-upgrade|disappear)
  ;;

  *)
    (>&2 echo "postrm called with unknown argument \`$1'")
    exit 1
  ;;

esac

exit 0
