#!/bin/sh

set -e

delete_service_files() {
  if [ -f "/lib/systemd/system/ledger-rest.service" ] ; then
    rm /lib/systemd/system/ledger-rest.service
  fi

  if [ -f "/lib/systemd/system/ledger-unit@.service" ] ; then
    rm /lib/systemd/system/ledger-unit@.service
  fi

  if [ -f "/lib/systemd/system/ledger.service" ] ; then
    rm /lib/systemd/system/ledger.service
  fi

  if [ -f "/lib/systemd/system/ledger.path" ] ; then
    rm /lib/systemd/system/ledger.path
  fi
}

delete_displace_files() {
  if [ -f "/etc/init/ledger.conf" ] ; then
    rm /etc/init/ledger.conf
  fi
}

case "$1" in

  purge)
    # userdel openbank || :

    delete_service_files
    delete_displace_files

    if [ -d /run/systemd/system ] ; then
      (systemctl daemon-reload || :)
      (systemctl reset-failed || :)
    fi
  ;;

  remove)
    if [ -d /run/systemd/system ] ; then
      (systemctl -a -t service --no-legend  | awk '$1 ~ /ledger/ { print $1 }' | xargs -I {} systemctl stop {} 2> /dev/null || :)
      (systemctl daemon-reload || :)
    fi

    delete_displace_files
  ;;

  upgrade|deconfigure)
    if [ -d /run/systemd/system ] ; then
      systemctl stop ledger 2> /dev/null || :
    fi
  ;;

  remove|failed-upgrade|abort-install|abort-upgrade|disappear)
  ;;

  *)
    (>&2 echo "postrm called with unknown argument \`$1'")
    exit 1
  ;;

esac

exit 0
