#!/bin/sh

set -e

case "$1" in

  configure)
    if [ -f "/etc/init/ledger.conf" ] ; then
      systemctl unmask \
        ledger.path \
        ledger-unit.service \
        ledger-rest.service \
        ledger.service \
      >/dev/null

      systemctl enable \
        ledger.path \
        ledger-rest.service \
        ledger.service \
      >/dev/null

      (systemctl start ledger.service >/dev/null || :)
    else
      (>&2 echo "/etc/init/ledger.conf file not found")
      exit 1
    fi
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
  ;;

  *)
    (>&2 echo "postinst called with unknown argument \ `$1`")
    exit 1
  ;;

esac

exit 0
