#!/bin/sh

set -e

if [ "$(ps -o comm -p 1 --no-headers | tr -d ' ')" = "systemd" ] ; then
  SYSTEMD_AVAIL=true
else
  SYSTEMD_AVAIL=false
fi

delete() {
  if [ -f "${1}" ] ; then
    rm "${1}"
  fi
}

delete_service_files() {
  delete /etc/systemd/ledger.service.wants/ledger-rest.service
  delete /lib/systemd/system/ledger-rest.service

  delete /etc/systemd/ledger.service.wants/ledger-unit@.service
  delete /lib/systemd/system/ledger-unit@.service

  delete /etc/systemd/ledger.service.wants/ledger.path
  delete /lib/systemd/system/ledger.path

  delete /etc/systemd/multi-user.target.wants/ledger.service
  delete /lib/systemd/system/ledger.service
}

delete_displace_files() {
  delete /etc/init/ledger.conf
}

case "$1" in

  purge)
    delete_service_files
    delete_displace_files

    if [ ${SYSTEMD_AVAIL} ] ; then
      (systemctl daemon-reload || :)
      (systemctl reset-failed || :)
    fi
  ;;

  remove)
    if [ ${SYSTEMD_AVAIL} ] ; then
      (systemctl -a -t service --no-legend  | awk '$1 ~ /ledger/ { print $1 }' | xargs -I {} systemctl stop {} 2> /dev/null || :)
    fi

    delete_displace_files

    if [ ${SYSTEMD_AVAIL} ] ; then
      (systemctl daemon-reload || :)
    fi
  ;;

  upgrade|deconfigure)
    if [ ${SYSTEMD_AVAIL} ] ; then
      (systemctl stop ledger 2> /dev/null || :)
    fi
  ;;

  remove|failed-upgrade|abort-install|abort-upgrade|disappear)
  ;;

  *)
    (>&2 echo "postrm called with unknown argument \`$1'")
    exit 1
  ;;

esac

exit 0
