.nh
.TH "LEDGER-UNIT" "1" "Jul 2020" "Ledger Unit" "OpenBank Account Ledger Manual"
.sp
.SH "NAME"
lake \-  starts openbank account ledger transaction unit
.SH "SYNOPSIS"
.sp
.nf
\fIledger-unit
.fi
.sp
.SH "DESCRIPTION"
.sp
The ledger unit stores transaction journal and negotiates transaction with
vault units
.sp
.SH "AUTHORS"
.sp
Jan Cajthaml <jan.cajthaml@gmail.com>
.sp
