.nh
.TH "LEDGER-REST" "1" "Jul 2020" "Vault Unit" "OpenBank Ledger REST Server Manual"
.sp
.SH "NAME"
lake \- starts openbank account ledger REST server
.SH "SYNOPSIS"
.sp
.nf
\fIledger-rest
.fi
.sp
.SH "DESCRIPTION"
.sp
The ledger rest provides REST server for accessing and manipulating ledger units
.sp
.SH "AUTHORS"
.sp
Jan Cajthaml <jan.cajthaml@gmail.com>
.sp
